name: Build Firmware

on:
  workflow_call:
    inputs:
      build_matrix:
        description: "Target file"
        default: "target.json"
        required: false
        type: string
      archive_name:
        description: "Archive name"
        default: "firmware"
        required: false
        type: string


jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          content=`cat ${{ inputs.build_matrix }}`
          echo "matrix=$(echo $content)" >> $GITHUB_OUTPUT

  build:
    needs: matrix
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli@sha256:a78acc2b7de1f476f33dd0d069c0e74ddfdb52c18b9a504c7cce32303cfa7aa2
    strategy:
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          path: target-repo

      - name: Checkout Vial-QMK
        uses: actions/checkout@v4
        with:
          repository: vial-kb/vial-qmk
          ref: 5c633c13a2cccbe0d295bdc6b38484ffa1b55527
          path: vial-qmk

      - name: Replace keyboards directory
        run: |
          rm -rf vial-qmk/keyboards
          cp -r target-repo/qmk_firmware/keyboards vial-qmk/

      - name: Setup QMK
        working-directory: vial-qmk
        run: |
          python3 -m pip install -r requirements.txt
          qmk setup -y

      - name: Build firmware
        working-directory: vial-qmk
        run: |
          make ${{ matrix.keyboard }}:${{ matrix.keymap }}:${{ matrix.target }} ${{ matrix.flags }}
          mv .build/${{ matrix.keyboard }}_${{ matrix.keymap }}.${{ matrix.target }} .build/${{ matrix.name }}.${{ matrix.target }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.name }}
          path: vial-qmk/.build/${{ matrix.name }}.${{ matrix.target }}

  merge:
    runs-on: ubuntu-latest
    needs: build
    name: Merge Artifacts
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ inputs.archive_name }}
          pattern: artifact-*
          delete-merged: true